[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://www.owlbear.rodeo"
    Access-Control-Allow-Methods = "GET, HEAD, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
    Cross-Origin-Resource-Policy = "cross-origin"
    Cross-Origin-Embedder-Policy = "unsafe-none"
